version: '3.1'

services: 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  portfolio:
    build: ..
    restart: always
    ports:
      - 8000:80
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_IP: db
      DJANGO_TOKEN: DEBUG_DJANGO_TOKEN