apiVersion: v1
kind: Service
metadata:
  namespace: portfolio
  name: portfolio
spec:
  type: NodePort
  selector:
    app: portfolio
  ports: 
    - port: 80
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: portfolio
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      volumes:
      - name: statics
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: tmp
        emptyDir: {}
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
          - name: statics
            mountPath: /usr/share/nginx/html/static
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: tmp
            mountPath: /tmp
        - name: frontend
          image: wearebrews/portfolio:dev
          imagePullPolicy: Always
          volumeMounts:
          - name: statics
            mountPath: /statics
          - name: tmp
            mountPath: /tmp
          resources:
            limits:
              cpu: "0.25"
              memory: "0.5Gi"
          env:
          - name: MYSQL_IP
            value: mysql
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            value: brew
        
