apiVersion: v1
kind: Namespace
metadata:
  name: portfolio
---
apiVersion: v1
kind: Service
metadata:
  namespace: portfolio
  name: portfolio
spec:
  selector:
    app: portfolio
  ports: 
    - port: 80
      name: http
---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: portfolio-ingress
      namespace: portfolio
      annotations:
        ingress.kubernetes.io/rewrite-target: /
    spec:
      rules:
      - http:
          paths:
          - path: /
            backend:
              serviceName: portfolio
              servicePort: http
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: portfolio
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: frontend
          image: wearebrews/portfolio:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
