apiVersion: v1
kind: Namespace
metadata:
  name: wearebrews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-main
  namespace: wearebrews
  labels:
    app: frontend-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-main
  template:
    metadata:
      labels:
        app: frontend-main
    spec:
      containers:
        - name: frontend-main
          image: wearebrews/frontend-main:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
