apiVersion: v1
kind: Service
metadata:
  namespace: portfolio
  name: portfolio
spec:
  type: NodePort
  selector:
    app: portfolio
  ports: 
    - port: 80
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: portfolio
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: frontend
          image: wearebrews/portfolio:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.25"
              memory: "0.5Gi"
          env:
          - name: MYSQL_IP
            value: mysql
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            value: brew
