apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: portfolio
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: havardmellbye@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
    
